dist: focal

jobs:
  include:
    - os: linux
      services: docker
      language: minimal
      install: skip
      addons:
        apt:
          packages:
          - pass
      env: DOCKER=spinalhdl/dev
      script: ./travis.sh -c
      deploy:
        provider: script
        cleanup: false
        script: ./travis.sh -d
        on:
          repo: SpinalHDL/SpinalHDL
          branch: master
#    - &host
#      language: scala
#      # See 'project/Version.scala'
#      scala: 2.11.12
#      jdk: openjdk9
#      sbt_args: -Dsbt.supershell=false -no-colors -J-Xss2m
#      script:
#        - sbt -jvm-opts travis/jvmopts.compile compile
#        - sbt -jvm-opts travis/jvmopts.test test
#      before_install:
#        - ./travis.sh -i
#        - export PATH=$(pwd)/../ghdl/usr/local/bin:$PATH
#        - export COCOTB=$(pwd)/../cocotb
#      before_cache:
#        # Tricks to avoid unnecessary cache updates
#        - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
#        - find $HOME/.sbt -name "*.lock" -delete
#      cache:
#        directories:
#          - $HOME/.ivy2/cache
#          - $HOME/.sbt/boot/
#    - <<: *host
#      jdk: openjdk10
#    - <<: *host
#      jdk: openjdk11
#    - <<: *host
#      jdk: openjdk7
#    - <<: *host
#      jdk: oraclejdk7
