# Copyright (c) 2020 Olof Kindgren <olof.kindgren@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

identifier: service
name: servant SoC for iCE40
type: mcu
arch: riscv32
toolchain:
  - zephyr
ram: 32
testing:
  ignore_tags:
    - net
    - bluetooth
